### ISSUE TITLE
Seeding postgresql database with date attribute 

### ISSUE THREAD

**Issue by luis-araujo-dev** [loadsys/CakePHP-Basic-Seed#16]
I'm trying to seed a postresql database with a validity attribute which is of the date type.

The seed successeds but the value it's different from want I'm expecting. This doesn't occurs with timestamp types. Is this a bug or am I doing something wrong? 

My seed file (http://pastebin.com/6xhQPESK): 

``` php
<?php
/**
 * BasicSeed plugin data seed file.
 */

namespace App\Config\BasicSeed;

use Cake\ORM\TableRegistry;

// Write your data import statements here.
$data = [
    'credit_cards' => [
        '_truncate' => true,
        '_defaults' => [],
        [
            'number' => '123',
            'type' => 'visa',
            'validity' => '2018-07-05',
            'created' => '2016-06-06 01:00:00',
            'modified' => '2016-06-06 01:00:00'
        ],
    ],
];

$this->importTables($data);
```

**Comment by beporter** [comment]
It's hard to say without having a bit more information. Can you post the table's schema as well? Cake will automatically try to convert data based on the column's type (which is how a string like `2018-07-05` gets turned into a `DateTime` object in your CreditCard entities), but that depends on how the database table is defined.

So along those lines, another thing to try would be to specify a DateTime object explicitly instead of just the string:

``` php
    'validity' => new \DateTime('2018-07-05'),
```

Try that and see if you get different results.

Another question that may get us on the right track: How far off is the value stored in the DB from the string in the seed file? Is it only 1 day? If so, you may be seeing a timezone issue and you may need to more explicitly define the date and time and timezone so it gets translated into the DB accurately and not 5 or 6 hours off (depending on what your machine's timezone is set to.)

**Comment by luis-araujo-dev** [comment]
Thank you for the fast response !

That works for me, the issue was solved with your solution. Thank you for the help. 

The value that appears in the database was 2173-02-07 when I put '2018-07-05'. So, it doesn't looks like it's a timezone issue.
If you need just more information from me, when trying to debug this, please just say it.

**Comment by beporter** [comment]
If you're satisfied, I'm satisfied. :grin: I'll close this out, but feel free to add anything if something pops up again.
