### ISSUE TITLE
Example Seed File?

### ISSUE THREAD

**Issue by gabehesse** [loadsys/CakePHP-Basic-Seed#8]
Can you please show a sample seed file creating like a user or something?  Pretty clueless about how the actual file should be structured.

**Comment by beporter** [comment]
That's a great question. The README could definitely do a better job of explaining the possibilities.

In it's most basic form, the BasicSeedShell just gives you a Cake runtime environment from which to load your data. Here are a few example `seed.php` files to give you some ideas:

---

This is the crudest possible method. Grab a copy of your user model, and tell it to save a record. Repeat for however many records you need in the seed.

``` php
<?php
App::uses('Security', 'Utility');

$admin = array(
    'User' => array(
        'id' => 1, // Locks us to id=1, which might not always be preferable.
        'username' => 'admin',
        'password' => Security::hash('password', 'blowfish'),
    ),
);

$User = ClassRegistry::init('User');
$User->create();
$result = $User->save($admin);
// Maybe do something here if $result is false?
```

---

The Shell currently includes a single method to assist in creating new records if they don't yet exist in the table and updating existing records if they do. It's a little more complicated to use, but allows you to match and update/reset existing records by a field other than the ID:

``` php
<?php
App::uses('Security', 'Utility');

$User = ClassRegistry::init('User');

$this->firstOrCreate(
    $User, // Act on this Model.
    array( // Try looking up an existing record using this.
        'username' => 'admin',
    ),
    array( // If no existing record, save both the above array and this one together as a new record.
        'password' => Security::hash('password', 'blowfish'),
    )
);
```

In this example, the ID of the `username=admin` record doesn't matter any more-- the seed will always create or update a record with username=admin and password=password.

I'm going to leave this issue open though, since we should add this to the README itself. Thanks for the question!

**Comment by beporter** [comment]
Since having been upgraded for compatibility with Cake 3 in #10, the readme now contains better notes on how to construct a seed file.
